version: 2
jobs:
  jabberwock: 
    machine: true
    steps:
      - run:
         name: Simple Step
         command: | 
            echo "Jabberwocky"
            exit 0
  build:
    docker: 
      - image: circleci/node:13.0.1-stretch-browsers
      - image: quay.io/influxdb/influx:nightly
        command: [ --e2e-testing=true ]
    steps: 
      - checkout
      - run: 
         name: Environment check 
         command: | 
           git --version
           node --version && npm --version
           docker --version
           google-chrome --version && which google-chrome && chromedriver --version && which chromedriver           
      - run:
         name: Checkout Tests
         command: git clone --single-branch --branch 2.0-Alpha https://github.com/bonitoo-io/selenium-accept-infl2.git 
      - run: 
         name: Selenium tests 
         command: | 
           set +e 
           cd selenium-accept-infl2
           npm install
           npm test; TEST_RESULT=$?
           sleep 30
           npm run report:html
           npm run report:junit 
           mkdir -p ~/test-results/cucumber
           mkdir -p ~/artefacts/html
           cp ~/project/selenium-accept-infl2/report/cucumber_report.html ~/artefacts/html/cucumber_report.html
           cp ~/project/selenium-accept-infl2/report/cucumber_junit.xml ~/test-results/cucumber/report.xml
           cp ~/project/selenium-accept-infl2/report/cucumber_junit.xml ~/artefacts/report.xml
           cp -r ~/project/selenium-accept-infl2/screenshots ~/artefacts
           ls -al
           exit $TEST_RESULT
      - store_test_results:
          path: ~/test-results
      - store_artifacts: 
          path: ~/artefacts

workflows:
   version: 2
   test: 
     jobs: 
      - jabberwock
      - build:
         requires: 
           - jabberwock

