version: 2
jobs: 
  build:
    docker: 
      - image: circleci/node:13.0.1-stretch-browsers
      - image: quay.io/influxdb/influx:nightly
        command: [ --e2e-testing=true ]
    steps: 
      - checkout
      - run: pwd && ls -al
      - run: 
         name: Greeting 
         command: echo Hello 
      - run: 
         name: It is now 
         command: date   
      - run: 
         name: Git check
         command: git --version
      - run: 
         name: Node check 
         command: node --version && npm --version
      - run: 
         name: Docker check 
         command: docker --version
      - run: 
         name: Chrome check 
         command: google-chrome --version && which google-chrome && chromedriver --version && which chromedriver
      - run: 
         name: Selenium tests 
         command: cd selenium-accept-infl2/ && npm test; npm run report:junit; npm run report:html 
      - run: 
         name: Save Test Results
         command: | 
           mkdir -p ~/test-results/cucumber
           mkdir -p ~/test-results/html
           mkdir -p ~/test-results/macabre
           pwd 
           cp ~/project/selenium-accept-infl2/report/cucumber_report.html ~/test-results/html/cucumber_report.html
           cp ~/project/selenium-accept-infl2/report/cucumber_report.json ~/test-results/cucumber/report.cucumber
           cp -r ~/project/selenium-accept-infl2/screenshots ~/test-results
      - store_test_results:
          path: ~/test-results
      - store_artifacts: 
          path: ~/test-results
