version: 2
jobs: 
  build:
    docker: 
      - image: circleci/node:13.0.1-stretch-browsers
      - image: quay.io/influxdb/influx:nightly
        command: [ --e2e-testing=true ]
    steps: 
      - checkout
      - run: pwd && ls -al
      - run: 
         name: Greeting 
         command: echo Hello 
      - run: 
         name: It is now 
         command: date   
      - run: 
         name: Git check
         command: git --version
      - run: 
         name: Node check 
         command: node --version && npm --version
      - run: 
         name: Docker check 
         command: docker --version
      - run: 
         name: Chrome check 
         command: google-chrome --version && which google-chrome && chromedriver --version && which chromedriver
      - run: 
         name: Connect Check 
         command: ./test-run.sh
      - run: 
         name: Save Test Results
         command: | 
           mkdir -p ~/cucumber
           pwd 
            cp ~/project/selenium-accept-infl2/report/cucumber_junit.xml ~/cucumber/junit.xml 
            cp ~/project/selenium-accept-infl2/report/cucumber_report.html ~/cucumber/cucumber_report.html
      - store_test_results:
          path: ~/cucumber
      - store_artifacts: 
          path: ~/cucumber
