version: 2
jobs: 
  build: 
    docker: 
      - image: circleci/node:13.0.1-stretch-browsers
    steps: 
      - checkout
      - run: pwd && ls -al
      - run: 
         name: Greeting 
         command: echo Hello 
      - run: 
         name: It is now 
         command: date   
